import { StyleSheet } from "react-native";
import fonts from "../../styles/fonts";

export const styles = StyleSheet.create({
  Container: {
    flex: 1,
    backgroundColor: "#f2f2f2",
    marginTop: 40,
    padding: 10,
  },
  TitleContainer: {
    alignItems: "center",
    marginVertical: 10,
    flexDirection: "row",
    justifyContent: "flex-start",
    width: "100%",
  },
  Title: {
    fontFamily: fonts.heading,
    fontSize: 22,
    color: "#333",
    flex: 1,
    textAlign: "center",
  },
  PrintButton: {
    backgroundColor: "#32B768",
    padding: 8,
    borderRadius: 8,
    marginRight: 10,
    elevation: 2,
  },
  ToggleModoContainer: {
    flexDirection: "row",
    alignSelf: "center",
    marginBottom: 8,
    backgroundColor: "#e5e7eb",
    borderRadius: 20,
    padding: 2,
  },
  ToggleButtonAtivo: {
    paddingHorizontal: 18,
    paddingVertical: 6,
    borderRadius: 18,
    backgroundColor: "#32B768",
    marginHorizontal: 2,
  },
  ToggleButtonInativo: {
    paddingHorizontal: 18,
    paddingVertical: 6,
    borderRadius: 18,
    backgroundColor: "transparent",
    marginHorizontal: 2,
  },
  ToggleTextAtivo: {
    color: "#fff",
    fontFamily: fonts.text,
    fontSize: 13,
  },
  ToggleTextInativo: {
    color: "#111827",
    fontFamily: fonts.text,
    fontSize: 13,
  },
  FilterContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  TextInput: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 6,
    paddingHorizontal: 12,
    height: 40,
    fontFamily: fonts.text,
    fontSize: 14,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  FilterButton: {
    backgroundColor: "#32B768",
    paddingHorizontal: 14,
    height: 40,
    borderRadius: 6,
    marginLeft: 8,
    justifyContent: "center",
  },
  ButtonDates: {
    backgroundColor: "#32B768",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 6,
  },
  ButtonDatesText: {
    color: "#fff",
    fontFamily: fonts.heading,
    fontSize: 13,
  },
  dates: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  Dates: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  pickDate: {
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 6,
    flex: 1,
    marginHorizontal: 4,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ddd",
  },
  date: {
    fontFamily: fonts.text,
    fontSize: 14,
    marginTop: 4,
  },
  CardContainer: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
    elevation: 2,
  },
  CardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  Cliente: {
    fontFamily: fonts.heading,
    fontSize: 16,
    color: "#333",
    flex: 1,
  },
  StatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  StatusText: {
    color: "#fff",
    fontFamily: fonts.text,
    fontSize: 11,
    fontWeight: "bold",
  },
  Valor: {
    fontFamily: fonts.text,
    fontSize: 18,
    color: "#222",
    marginBottom: 8,
    fontWeight: "bold",
  },
  Section: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  Icon: {
    marginRight: 6,
  },
  InfoText: {
    fontFamily: fonts.text,
    fontSize: 13,
    color: "#555",
  },
  Descricao: {
    fontFamily: fonts.text,
    fontSize: 12,
    color: "#666",
    marginTop: 6,
    fontStyle: "italic",
  },
  Actions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 10,
    gap: 16,
  },
  EmptyContainer: {
    alignItems: "center",
    marginTop: 40,
  },
  EmptyText: {
    fontFamily: fonts.text,
    fontSize: 16,
    color: "#999",
    marginTop: 10,
  },
  FloatContainer: {
    position: "absolute",
    bottom: 20,
    right: 20,
  },
  FloatButton: {
    backgroundColor: "#32B768",
    width: 55,
    height: 55,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
  },
  ModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  ModalContent: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 20,
    width: "85%",
    maxHeight: "70%",
  },
  CloseButton: {
    alignSelf: "flex-end",
  },
  ModalTitle: {
    fontFamily: fonts.heading,
    fontSize: 18,
    color: "#333",
    marginBottom: 8,
  },
  ModalValor: {
    fontFamily: fonts.text,
    fontSize: 20,
    color: "#222",
    fontWeight: "bold",
    marginBottom: 16,
  },
  ModalSection: {
    marginBottom: 12,
  },
  ModalLabel: {
    fontFamily: fonts.heading,
    fontSize: 13,
    color: "#666",
    marginBottom: 4,
  },
  ModalValue: {
    fontFamily: fonts.text,
    fontSize: 14,
    color: "#333",
  },
});
