import { Platform, StyleSheet } from "react-native";
import fonts from "../../styles/fonts";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f3f7f6",
  },
  flexOne: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingTop: Platform.OS === "android" ? 18 : 8,
    paddingBottom: 6,
    backgroundColor: "#f3f7f6",
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  logo: {
    width: 72,
    height: 72,
    resizeMode: "contain",
  },
  content: {
    paddingHorizontal: 18,
    paddingBottom: 32,
    gap: 16,
  },
  heroCard: {
    backgroundColor: "#0f766e",
    borderRadius: 24,
    padding: 22,
    shadowColor: "#115e59",
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 4,
  },
  heroBadge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.18)",
    color: "#ecfeff",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    fontSize: 12,
    fontFamily: fonts.heading,
    overflow: "hidden",
    marginBottom: 10,
  },
  heroTitle: {
    fontSize: 26,
    lineHeight: 32,
    color: "#ffffff",
    fontFamily: fonts.heading,
    marginBottom: 8,
  },
  heroSubtitle: {
    fontSize: 15,
    lineHeight: 22,
    color: "#d1fae5",
    fontFamily: fonts.text,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 22,
    padding: 18,
    shadowColor: "#0f172a",
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 18,
    color: "#0f172a",
    fontFamily: fonts.heading,
    marginBottom: 14,
  },
  dateRow: {
    flexDirection: "row",
    gap: 12,
  },
  dateButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: "#f8fafc",
  },
  dateLabel: {
    fontSize: 12,
    color: "#64748b",
    fontFamily: fonts.text,
    marginBottom: 6,
  },
  dateValue: {
    fontSize: 16,
    color: "#0f172a",
    fontFamily: fonts.heading,
  },
  pickerBox: {
    marginTop: 14,
    borderRadius: 18,
    backgroundColor: "#f8fafc",
    padding: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  pickerCloseButton: {
    alignSelf: "flex-end",
    backgroundColor: "#0f766e",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginTop: 10,
  },
  pickerCloseButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontFamily: fonts.heading,
  },
  label: {
    fontSize: 14,
    color: "#334155",
    fontFamily: fonts.heading,
    marginBottom: 8,
    marginTop: 8,
    marginLeft: 2,
  },
  hiddenLabel: {
    display: "none",
  },
  selectContainer: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 18,
    paddingHorizontal: 14,
    height: 54,
    justifyContent: "center",
    marginHorizontal: 0,
    marginTop: 0,
    backgroundColor: "#f8fafc",
  },
  loadingBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 12,
  },
  loadingText: {
    fontSize: 14,
    color: "#475569",
    fontFamily: fonts.text,
  },
  helperInfo: {
    marginTop: 10,
    fontSize: 12,
    lineHeight: 18,
    color: "#0f766e",
    fontFamily: fonts.text,
  },
  detectedTermsBox: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#d1fae5",
    backgroundColor: "#f0fdfa",
    borderRadius: 14,
    padding: 12,
  },
  detectedTermsTitle: {
    fontSize: 12,
    lineHeight: 18,
    color: "#0f766e",
    fontFamily: fonts.heading,
    marginBottom: 8,
  },
  detectedTermsEmpty: {
    fontSize: 12,
    lineHeight: 18,
    color: "#64748b",
    fontFamily: fonts.text,
  },
  detectedTermsWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  detectedTermChip: {
    borderRadius: 999,
    backgroundColor: "#ccfbf1",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  detectedTermText: {
    fontSize: 12,
    color: "#134e4a",
    fontFamily: fonts.heading,
  },
  actionsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  primaryButton: {
    flex: 1,
    minHeight: 52,
    backgroundColor: "#0f766e",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 12,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontFamily: fonts.heading,
  },
  secondaryButton: {
    minWidth: 96,
    minHeight: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e2e8f0",
    paddingHorizontal: 14,
  },
  secondaryButtonText: {
    color: "#334155",
    fontSize: 14,
    fontFamily: fonts.heading,
  },
  previewBox: {
    marginTop: 14,
    borderRadius: 16,
    backgroundColor: "#ecfeff",
    padding: 14,
    borderWidth: 1,
    borderColor: "#a5f3fc",
  },
  previewLabel: {
    fontSize: 12,
    color: "#0f766e",
    fontFamily: fonts.heading,
    marginBottom: 4,
  },
  previewText: {
    fontSize: 14,
    color: "#164e63",
    fontFamily: fonts.text,
  },
  chipsWrap: {
    marginTop: 16,
    gap: 10,
  },
  groupedChipTitle: {
    fontSize: 12,
    color: "#0f766e",
    fontFamily: fonts.heading,
    marginBottom: 8,
    marginLeft: 2,
  },
  filterChip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    backgroundColor: "#f8fafc",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  filterChipTextBox: {
    flex: 1,
    paddingRight: 10,
  },
  filterChipPlan: {
    fontSize: 12,
    color: "#0f766e",
    fontFamily: fonts.heading,
    marginBottom: 2,
  },
  filterChipText: {
    fontSize: 14,
    color: "#0f172a",
    fontFamily: fonts.text,
  },
  emptyText: {
    fontSize: 14,
    color: "#64748b",
    fontFamily: fonts.text,
    lineHeight: 21,
  },
  autoButton: {
    marginTop: 18,
    minHeight: 54,
    backgroundColor: "#111827",
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 14,
  },
  autoButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontFamily: fonts.heading,
  },
  summaryHint: {
    fontSize: 13,
    color: "#64748b",
    lineHeight: 20,
    fontFamily: fonts.text,
    marginBottom: 14,
  },
  summaryStatus: {
    fontSize: 13,
    color: "#0f766e",
    lineHeight: 20,
    fontFamily: fonts.heading,
    marginBottom: 12,
  },
  printButton: {
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#f8fafc",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 12,
  },
  printButtonText: {
    fontSize: 14,
    color: "#0f172a",
    fontFamily: fonts.heading,
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  metricCard: {
    width: "48%",
    borderRadius: 18,
    padding: 14,
    minHeight: 94,
    justifyContent: "space-between",
  },
  metricIncomeCard: {
    backgroundColor: "#dcfce7",
  },
  metricIncomeCardLight: {
    backgroundColor: "#ecfccb",
  },
  metricExpenseCardLight: {
    backgroundColor: "#fee2e2",
  },
  metricExpenseCard: {
    backgroundColor: "#fecaca",
  },
  metricLabel: {
    fontSize: 13,
    color: "#334155",
    fontFamily: fonts.heading,
  },
  metricValuePositive: {
    fontSize: 19,
    color: "#166534",
    fontFamily: fonts.heading,
  },
  metricValueNeutral: {
    fontSize: 19,
    color: "#1e293b",
    fontFamily: fonts.heading,
  },
  metricValueNegative: {
    fontSize: 19,
    color: "#991b1b",
    fontFamily: fonts.heading,
  },
  resultCard: {
    marginTop: 16,
    borderRadius: 20,
    padding: 18,
    backgroundColor: "#0f172a",
  },
  resultLabel: {
    fontSize: 13,
    color: "#cbd5e1",
    fontFamily: fonts.heading,
    marginBottom: 6,
  },
  resultValuePositive: {
    fontSize: 28,
    color: "#86efac",
    fontFamily: fonts.heading,
  },
  resultValueNegative: {
    fontSize: 28,
    color: "#fca5a5",
    fontFamily: fonts.heading,
  },
  resultPercent: {
    marginTop: 6,
    fontSize: 12,
    color: "#cbd5e1",
    fontFamily: fonts.text,
  },
  workSummaryRow: {
    marginTop: 12,
    flexDirection: "row",
    gap: 10,
  },
  workSummaryCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 14,
    padding: 12,
    backgroundColor: "#f8fafc",
  },
  workSummaryLabel: {
    fontSize: 12,
    color: "#334155",
    fontFamily: fonts.heading,
    marginBottom: 6,
  },
  workSummaryValuePositive: {
    fontSize: 17,
    color: "#166534",
    fontFamily: fonts.heading,
  },
  workSummaryValueNegative: {
    fontSize: 17,
    color: "#991b1b",
    fontFamily: fonts.heading,
  },
  workSummaryPercent: {
    marginTop: 4,
    fontSize: 12,
    color: "#64748b",
    fontFamily: fonts.text,
  },
  itemRow: {
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 18,
    padding: 14,
    backgroundColor: "#f8fafc",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  itemTexts: {
    flex: 1,
  },
  itemTitle: {
    fontSize: 15,
    color: "#0f172a",
    fontFamily: fonts.heading,
    marginBottom: 4,
  },
  itemSubtitle: {
    fontSize: 13,
    color: "#475569",
    fontFamily: fonts.text,
    marginBottom: 2,
  },
  itemMeta: {
    fontSize: 12,
    color: "#64748b",
    fontFamily: fonts.text,
    marginTop: 4,
  },
  itemValueBox: {
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  itemBadge: {
    fontSize: 12,
    color: "#0f766e",
    fontFamily: fonts.heading,
    backgroundColor: "#ccfbf1",
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  itemValue: {
    fontSize: 16,
    color: "#111827",
    fontFamily: fonts.heading,
  },
});
