import { StyleSheet } from "react-native";
import fonts from "../../styles/fonts";

export const styles = StyleSheet.create({
  containerBusca: {
    flexDirection: "row",
    paddingHorizontal: 14,
    paddingTop: 10,
    alignItems: "center",
    backgroundColor: "#f3f4f6",
  },
  inputBusca: {
    flex: 1,
    borderWidth: 0,
    borderRadius: 20,
    paddingHorizontal: 14,
    height: 42,
    marginRight: 8,
    backgroundColor: "#ffffff",
    fontFamily: fonts.text,
    fontSize: 14,
    elevation: 1,
  },
  buttonBusca: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#32B768",
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
  },
  buttonNovo: {
    flexDirection: "row",
    marginHorizontal: 14,
    marginTop: 8,
    marginBottom: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: "#16a34a",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
  },
  buttonNovoText: {
    color: "#fff",
    marginLeft: 6,
    fontFamily: fonts.heading,
    fontSize: 14,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    marginHorizontal: 10,
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  cardTitle: {
    fontFamily: fonts.heading,
    fontSize: 16,
    color: "#111827",
  },
  cardDesc: {
    fontFamily: fonts.text,
    fontSize: 13,
    marginTop: 4,
    color: "#4b5563",
  },
  cardMeta: {
    fontFamily: fonts.text,
    fontSize: 12,
    marginTop: 6,
    color: "#6b7280",
  },
  cardBadgeInativo: {
    fontSize: 11,
    color: "#dc2626",
    fontFamily: fonts.text,
  },
  modalContainer: {
    flex: 1,
    padding: 16,
    backgroundColor: "#f3f4f6",
  },
  label: {
    fontFamily: fonts.text,
    fontSize: 13,
    marginTop: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontFamily: fonts.text,
    fontSize: 13,
    marginTop: 4,
  },
  materialRow: {
    marginTop: 8,
    padding: 10,
    borderRadius: 10,
    backgroundColor: "#e5e7eb",
  },
  materialProduto: {
    flexDirection: "row",
    alignItems: "center",
  },
  materialProdutoText: {
    flex: 1,
    fontFamily: fonts.text,
    fontSize: 13,
  },
  materialIdInput: {
    width: 60,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 4,
    marginLeft: 8,
    fontFamily: fonts.text,
    fontSize: 12,
    textAlign: "center",
  },
  buttonRemoverMaterial: {
    marginLeft: 8,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#ef4444",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonAddMaterial: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    borderRadius: 20,
    backgroundColor: "#32B768",
    paddingVertical: 10,
  },
  buttonAddMaterialText: {
    marginLeft: 6,
    color: "#fff",
    fontFamily: fonts.heading,
    fontSize: 13,
  },
  modalButtonsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
  },
  modalButton: {
    flex: 1,
    marginHorizontal: 4,
    paddingVertical: 12,
    borderRadius: 20,
    alignItems: "center",
  },
  modalButtonText: {
    color: "#fff",
    fontFamily: fonts.heading,
    fontSize: 14,
  },
});
